### ISSUE TITLE
Unable to delete highlight/hide block when clicking outside canvas during the block creation

### ISSUE THREAD

**Issue by felipefrm** [ColonelParrot/feedbackplus#1]
Hi @ColonelParrot! Congrats for your work!

Testing the demo, I noticed a small bug, here's the step by step on how to reproduce it:

  1. Start creating a highlight/hide block by pressing the mouse on the canvas.
  2. drag the mouse down outside the modal
  3. click outside the modal
  4. Return the mouse to the modal, and finish creating the block, clicking again on the canvas.

As a result of this flow, the created block does not have a delete button. Making it impossible to delete it.

**Comment by grantmgci2025** [comment]
Hey there,

I've successfully reproduced this issue. I'll fix it ASAP!

**Comment by ColonelParrot** [comment]
Thanks for the report!

I've reproduced the issue and I'm fixing it ASAP.

**Comment by ColonelParrot** [comment]
Will get a fix in place by Tuesday. Sorry, just been so swamped lately :)

Thanks for being so patient!

**Comment by ColonelParrot** [comment]
Hello,

Thanks for the patience & the report.

I've fixed the issue in v1.4.0!

**Comment by felipefrm** [comment]
Hi,

Awesome! You're doing a good job with this lib  :)
